[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "283415f7022adc76e73859d179687e25d9a6fb45d74f311ec9451a67b6a6a7da"

[auth.microsoft]
client_id = "57c7230e-66ca-41b7-9b80-eff68641b679"
client_secret = "nuV8Q~3lo3GYe.ybpLZyGPtzPeSwiSxtOhd~2b9Q"
server_metadata_url = "https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration"
redirect_uri = "http://localhost:8501/oauth2callback"